### ISSUE TITLE
Fork sdk and add token options

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/od-app#4]
Similar to #13 but for contracts 

Optimism-Goerli options: 

OP - Optimism: `0x4200000000000000000000000000000000000042`
WETH - Wrapped ETH: `0x4200000000000000000000000000000000000006`
wBTC - Wrapped Bitcoin: `0xf1fdb809f41c187ce6f2a4c8cc6562ba7479b4ef`
Stones - `0x4fc4cb45a812ae5d85be39b6d7fc9d169405a31f`

Optimism (use the existing values from the app)

stETH - Lido Staked ETH 
rETH - Rocket Pool ETH
and more...

Note: more may be added in the future

### TODO

- [ ] Get contract addresses for each asset
- [ ] Create a configuration file which accepts a network and returns details for name, symbol, decimals, contract address

**Comment by pi0neerpat** [comment]
@cupOJoseph will add the test token addresses

**Comment by jahabeebs** [comment]
@pi0neerpat The token addresses are currently being fetched from the hai-on-op SDK here: https://github.com/hai-on-op/sdk/blob/a8300a94a1fde4d65bcc75ae7df626ed8fbdfe19/src/contracts/addreses.ts#L192

The token addresses are then fetched in the application like this in connectWalletModal.ts: 
```
        const tokenList = payload.geb.tokenList
        const fetched = await fetchTokenData(payload.geb, payload.user, tokenList)
```

If we want to use our own addresses for the 'optimism-goerli' array in the SDK I can modify it from our application, but I wanted to check with you about two things:

1) in the array below do we need to modify collateralJoin, collateralAuctionHouse, isCollateral, etc or do we only need to modify the address? 

2) I suppose for this issue you want everything to be in a configuration file so I'll likely have to extract this whole contract variable and its interfaces to use in our own app since we're not using the values from the SDK. Alternatively, we could have the configuration file only have our modified values and then modify the tokenList fetched from the SDK to have our custom addresses. Which do you prefer?

```
const tokens: Record<GebDeployment, TokenList> = {
    mainnet: {},
    'optimism-goerli': {
        WETH: {
            address: '0x4200000000000000000000000000000000000006',
            decimals: 18,
            symbol: 'WETH',
            bytes32String: WETH,
            collateralJoin: '0x69DE387041C3056ec96aEFb432A546EAe4394da6',
            collateralAuctionHouse: '0x166425Cc84996DC0d8fEaDa66F86055AAE8f8209',
            isCollateral: true,
        },
        OP: {
            address: '0x4200000000000000000000000000000000000042',
            decimals: 18,
            symbol: 'OP',
            bytes32String: OP,
            collateralJoin: '0xA59A8a069284e52B8c761d7e0AC2129733ACCBF6',
            collateralAuctionHouse: '0xeAfB6be474e84fC5f3aF7bbaD39D89A5764D4D36',
            isCollateral: true,
        },
        WBTC: {
            address: '0xf1FDB809f41c187cE6F2A4C8cC6562Ba7479B4EF',
            decimals: 8,
            symbol: 'WBTC',
            bytes32String: WBTC,
            collateralJoin: '0x187Bcd738ca9fDDfC2439A7Cd537C05F85C40429',
            collateralAuctionHouse: '0x724A7b53c0B81DDB0654e012c94667730CBa1837',
            isCollateral: true,
        },
        STN: {
            address: '0x4FC4CB45A812AE5d85bE39b6D7fc9D169405a31F',
            decimals: 3,
            symbol: 'STN',
            bytes32String: STONES,
            collateralJoin: '0x78c64A263F685f98A83412A6891706cFa7eA29BB',
            collateralAuctionHouse: '0x22a804F6685f96dE8CD81aba0C85fe49884274f8',
            isCollateral: true,
        },
        TTM: {
            address: '0xE3Efbd4fafD521dAEa38aDC6D1A1bD66583D5da4',
            decimals: 0,
            symbol: 'TTM',
            bytes32String: TOTEM,
            collateralJoin: '0xC396AC5dc7e35c0BA7dca51b5eedbdd6055b91dB',
            collateralAuctionHouse: '0x24CF3ddF28d7a2e046Ea9bD1B6908D8B33AAB873',
            isCollateral: true,
        },
        HAI: {
            address: '0xEaE90F3b07fBE00921173298FF04f416398f7101',
            decimals: 18,
            symbol: 'HAI',
            bytes32String: '',
            collateralJoin: '0x3217B0aBcaAC50898F4826f0C502dEd9AB8eae53',
            collateralAuctionHouse: '0x0000000000000000000000000000000000000000',
            isCollateral: false,
        },
        KITE: {
            address: '0x64ff820bbD2947B2f2D4355D4852F17eb0156D9A',
            decimals: 18,
            symbol: 'KITE',
            bytes32String: '',
            collateralJoin: '',
            collateralAuctionHouse: '',
            isCollateral: false,
        },
    },
}
```

**Comment by pi0neerpat** [comment]
Lets fork the SDK to open-dollar-sdk
